"""[ToneSwitcher] From a single Markdown completion report, generate three
versions of the message at once, each tailored to its channel's culture
(Slack / Teams / client-facing email).

If a Claude API key is configured, the text is generated by AI; otherwise it
falls back to the built-in templates.
"""

import logging
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from . import llm
from .config import ensure_output_dir

logger = logging.getLogger("omnifuse")

TONES = ["slack", "teams", "email"]
TONE_LABELS = {"slack": "Slack (casual)", "teams": "Teams (business memo)",
               "email": "Email (client-facing)"}


# ------------------------------------------------------------ clipboard

def copy_to_clipboard(text: str) -> bool:
    try:
        if sys.platform == "darwin":
            subprocess.run(["pbcopy"], input=text.encode("utf-8"), check=True)
        elif sys.platform.startswith("win"):
            subprocess.run(["clip"], input=text.encode("utf-16-le", errors="replace"),
                           check=True)
        else:
            subprocess.run(["xclip", "-selection", "clipboard"],
                           input=text.encode("utf-8"), check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        logger.warning("Failed to copy to clipboard (the draft file was still saved)")
        return False


# ---------------------------------------------------------------- parsing

def _parse_report(md_text: str) -> dict:
    """Extract the title, key points, and body from a Markdown report."""
    title_match = re.search(r"^#\s+(.+)", md_text, re.M)
    title = title_match.group(1).strip() if title_match else "Completion Report"
    bullets = [re.sub(r"^\s*[-*]\s+", "", l).strip()
               for l in md_text.splitlines() if re.match(r"^\s*[-*]\s+", l)]
    paragraphs = [l.strip() for l in md_text.splitlines()
                  if l.strip() and not l.startswith("#")
                  and not re.match(r"^\s*[-*]\s+", l)]
    return {"title": title, "bullets": bullets, "paragraphs": paragraphs}


# -------------------------------------------------------- template generation

def _template_slack(report: dict) -> str:
    lines = [f":white_check_mark: *{report['title']}* is done! :tada:", ""]
    if report["bullets"]:
        lines.append("*What I did*")
        lines += [f"• {b}" for b in report["bullets"][:8]]
    if report["paragraphs"]:
        lines += ["", report["paragraphs"][0]]
    lines += ["", "Feel free to ping me if anything's unclear :pray:"]
    return "\n".join(lines)


def _template_teams(report: dict) -> str:
    today = datetime.now().strftime("%Y/%m/%d")
    lines = ["[Notice] Work Completion Report", "",
             f"Subject: {report['title']}", f"Completed: {today}", "", "■ Work done"]
    if report["bullets"]:
        lines += [f"- {b}" for b in report["bullets"]]
    elif report["paragraphs"]:
        lines += [f"- {p}" for p in report["paragraphs"][:5]]
    lines += ["", "■ Notes"]
    lines.append(report["paragraphs"][0] if report["paragraphs"] else "No special notes.")
    lines += ["", "Please review at your convenience. Thank you."]
    return "\n".join(lines)


def _template_email(report: dict, signature: str, sender: str) -> str:
    lines = [f"Subject: [Completion Report] {report['title']}", "", "Hello,"]
    lines += ["",
              f"I am writing to let you know that the requested work, "
              f"\"{report['title']}\", has been completed.", ""]
    if report["bullets"]:
        lines.append("Work completed:")
        lines += [f"- {b}" for b in report["bullets"]]
        lines.append("")
    if report["paragraphs"]:
        lines += [report["paragraphs"][0], ""]
    lines += ["Please don't hesitate to reach out if you have any questions or requests.",
              "Thank you, and best regards."]
    if sender:
        lines += ["", sender]
    if signature:
        lines += ["", "----------------", signature]
    return "\n".join(lines)


# ---------------------------------------------------------------- AI generation

_AI_SYSTEM = (
    "You are a professional business writer. "
    "Rewrite the given completion-report Markdown to match the culture of the "
    "specified channel. Output only the message body, with no preamble or explanation."
)

_AI_PROMPTS = {
    "slack": "Rewrite the completion report below as a casual, friendly internal Slack "
             "progress update. Use emoji in moderation and keep it concise, mostly "
             "bullet points.\n\n---\n{md}",
    "teams": "Rewrite the completion report below as a polite Microsoft Teams business "
             "notice. Start with \"[Notice]\" and organize it with ■ headings and bullet "
             "points.\n\n---\n{md}",
    "email": "Rewrite the completion report below as a polite, client-facing business "
             "email (with a subject line). Include an opening greeting and a closing.\n\n---\n{md}",
}


# ---------------------------------------------------------------- entry point

def switch(config: dict, md_path: str, clipboard_tone: str | None = "slack") -> dict:
    """Generate the three tones and save drafts. Returns {tone: (text, path)}."""
    path = Path(md_path)
    if not path.is_file():
        raise FileNotFoundError(f"Markdown file not found: {md_path}")
    md_text = path.read_text(encoding="utf-8")
    if not md_text.strip():
        raise ValueError("The report file is empty.")

    report = _parse_report(md_text)
    tone_cfg = config["tone"]
    use_ai = llm.is_available(config)
    logger.info("Text generation mode: %s", "Claude API" if use_ai else "template")

    results = {}
    for tone in TONES:
        text = None
        if use_ai:
            text = llm.generate(config, _AI_SYSTEM, _AI_PROMPTS[tone].format(md=md_text))
        if not text:
            if tone == "slack":
                text = _template_slack(report)
            elif tone == "teams":
                text = _template_teams(report)
            else:
                text = _template_email(report, tone_cfg.get("signature", ""),
                                       tone_cfg.get("sender_name", ""))
        results[tone] = text

    out_dir = ensure_output_dir(config) / "drafts"
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    saved = {}
    for tone, text in results.items():
        out_path = out_dir / f"{path.stem}_{tone}_{stamp}.txt"
        out_path.write_text(text, encoding="utf-8")
        saved[tone] = (text, out_path)
        logger.info("Saved draft: %s", out_path)

    if clipboard_tone and tone_cfg.get("copy_to_clipboard", True):
        if copy_to_clipboard(results[clipboard_tone]):
            logger.info("Copied the %s version to the clipboard", clipboard_tone)

    return saved
